config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  resource :posts
  root "posts#index"

  resources:user_monsters, only: [:new, :create, :index]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  has_one_attached :image_upload
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :user_monsters
  has_many :monster, through: :user_monsters
  #has_one_attached :image　carrierwaveを使用したためコメントアウト
  #1つのモンスター画像と紐づく
  mount_uploader :image, MonsterImageUploader #carrierwaveを使用
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :content, presence: true, length: { maximum: 150}
  #文字数０は認めない、151文字以上も認めない
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :user_monsters
  has_many :monsters, through: :user_monsters

end

app/models/user_monster.rb
class UserMonster < ApplicationRecord
  belongs_to :user
  belongs_to :monster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    root_path  # ログイン後、投稿一覧へリダイレクト
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/images_controller.rb
require 'open-uri'

class ImagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @image = current_user.images.build
  end

  def create
    @image = current_user.images.build(image_params)

    if @image.save
      generate_and_save_dalle_image(@image)
      redirect_to @image, notice: '画像を生成しました。'
    else
      render :new
    end
  end

  def show
    @image = current_user.images.find(params[:id])
  end

  private

  def image_params
    params.require(:image).permit(:image_title)
  end

  def generate_and_save_dalle_image(image)
    # DALL-E APIを呼び出して画像を生成
    client = OpenAI::Client.new(access_token: ENV['OPENAI_API_KEY'])
    response = client.images.generate(parameters: { prompt: image.image_title, size: "256x256" }) # promptにimage_titleを使用
    dall_e_image_url = response.dig("data", 0, "url")
    image.update(dall_e_image_url: dall_e_image_url)

    # 生成された画像をS3に保存
    downloaded_image = URI.open(dall_e_image_url)
    s3 = Aws::S3::Resource.new(region: ENV['AWS_REGION'], access_key_id: ENV['AWS_ACCESS_KEY_ID'], secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'])
    bucket = s3.bucket(ENV['AWS_S3_BUCKET'])
    object = bucket.object("images/#{image.id}.png")
    object.upload_file(downloaded_image.path)
    image.update(s3_image_url: object.public_url)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy] # ログイン必須
  before_action :correct_user, only: [:edit, :update, :destroy]


  def index #ユーザーのすべての投稿がタイムライン形式で表示されるように後で設定
    @posts = Post.includes(:user).order(created_at: :desc)#最新の投稿の順番
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "投稿が作成されました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: "投稿が更新されました"
    else
      render :edit
    end
  end

  def destroy
    @post = current_user.posts.find_by(id: params[:id]) #ここのparamsはどのような動きをしている？要確認
    if @post
      @post.destroy
      redirect_to posts_path, notice: "投稿を削除しました"
    else
      redirect_to posts_path, alert: "削除できませんでした"
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def correct_user #自身の投稿のみ編集、破棄が可能
    redirect_to posts_path, alert: "権限がありません" unless @post.user == current_user
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/user_monsters_controller.rb
class UserMonstersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_monsters = current_user.user_monsters.includes(:monster)
  end

  def new
    @user_monster = UserMonster.new
    @monsters = Monster.all
  end

  def create
    @user_monster = current_user.user_monsters.build(user_monster_params)
    if @user_monster.save
      redirect_to user_monsters_path, notice: 'モンスターを登録しました。'
    else
      @monsters = Monster.all
      render :new
    end
  end

  private

  def user_monster_params
    params.require(:user_monster).permit(:monster_id, :monster_name, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_monsters_helper.rb
module UserMonstersHelper
end

app/views/images/new.html.erb
<h1>モンスターを生成</h1>

<%= form_with model: @image, url: images_path, local: true do |form| %>
  <div class="field">
    <%= form.label :image_title, "廃棄せざるおえなくなったものの品名や特徴を記してください" %>
    <%= form.text_area :image_title %>
  </div>

  <div class="actions">
    <%= form.submit "モンスターを生成", class: "btn btn-primary" %>
  </div>
<% end %>

<% if @image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

    <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/images/show.html.erb
<% if @image.s3_image_url.present? %>
  <img src="<%= @image.s3_image_url %>" alt="生成された画像">
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MottainaiMonsters2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to "投稿一覧", root_path %> |
        <%= link_to "新規投稿", new_post_path %> |
        <%= link_to "祟りの部屋", new_image_path %>
        <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path %> |
        <%= link_to "新規登録", new_user_registration_path %>
      <% end %>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |f| %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content, rows: 3 %>
  </div>
  <%= f.submit "保存", class: "btn btn-success" %>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿を編集</h1>
<%= render "form", post: @post %>
<%= link_to "投稿一覧", posts_path, class: "btn btn-secondary" %>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <strong>ユーザー名:<%= post.user.email %></strong>:
      <%= post.content %>
      <% if user_signed_in? && post.user == current_user %>
        <%= link_to "削除", post_path(post), data: { turbo_method: :delete, confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
        <%= link_to "編集", edit_post_path(post), class: "btn btn-dager" %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h1>新しい投稿</h1>
<%=  render "form", post: @post %>
<%= link_to "投稿一覧", posts_path, class: "btn btn-secondary" %>

app/views/user_monsters/index.html.erb
<h1>登録モンスター一覧</h1>

<table>
  <thead>
    <tr>
      <th>モンスター画像</th>
      <th>モンスター名</th>
      <th>メッセージ</th>
    </tr>
  </thead>
  <tbody>
    <% @user_monsters.each do |user_monster| %>
      <tr>
        <td><%= image_tag user_monster.monster.image.url, size: '100x100' %></td>
        <td><%= user_monster.monster_name %></td>
        <td><%= user_monster.message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'モンスター登録', new_user_monster_path %>

app/views/user_monsters/new.html.erb
<h1>モンスター登録</h1>

<%= form_with model: @user_monster, local: true do |form| %>
  <div>
    <%= form.label :monster_id, 'モンスターの種類' %>
    <div class="monsters">
      <% @monsters.each do |monster| %>
        <label>
          <%= form.radio_button :monster_id, monster.id %>
          <%= monster.name %>
          <%= image_tag monster.image.url, size: '100x100' %>
        </label>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.label :monster_name, 'モンスター名' %>
    <%= form.text_field :monster_name %>
  </div>

  <div>
    <%= form.label :message, '贖罪の言葉' %>
    <%= form.text_area :message %>
  </div>
  <%= form.submit '登録' %>
<% end %>

<%= link_to '登録モンスター一覧', user_monsters_path %>